// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIXdxU5tFvkF1mV6BdxlvTeswFgwc3Yu4',
    appId: '1:987746696548:web:624cee211212f8763ace71',
    messagingSenderId: '987746696548',
    projectId: 'myawesomnotes',
    authDomain: 'myawesomnotes.firebaseapp.com',
    storageBucket: 'myawesomnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOr3YH4CRDp6p9vFT-9cf81e-bYYeGde8',
    appId: '1:987746696548:android:8ef260094b8bda983ace71',
    messagingSenderId: '987746696548',
    projectId: 'myawesomnotes',
    storageBucket: 'myawesomnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnYXtWDFlvLAgFUBTgbxsyabNP77WIZ08',
    appId: '1:987746696548:ios:f0ad2d5b78df09c33ace71',
    messagingSenderId: '987746696548',
    projectId: 'myawesomnotes',
    storageBucket: 'myawesomnotes.appspot.com',
    iosClientId: '987746696548-hb1d3inonrfotq33stfv376hg3ghfs4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnYXtWDFlvLAgFUBTgbxsyabNP77WIZ08',
    appId: '1:987746696548:ios:f0ad2d5b78df09c33ace71',
    messagingSenderId: '987746696548',
    projectId: 'myawesomnotes',
    storageBucket: 'myawesomnotes.appspot.com',
    iosClientId: '987746696548-hb1d3inonrfotq33stfv376hg3ghfs4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
